# Uncomment this file to enable multilanguage site support

#[en]
#languageName = "English"
#languagedirection = "ltr"
#title = "Example Site"
#weight = 1

[ko]
languageName = "Korean"
title = "kjs92980"
description = "kjs92980의 블로그"
weight = 1
